import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/page-sections/header";
import Footer from "@/page-sections/footer";

const montserrat = Montserrat({
  subsets: ["latin"],
  preload: true,
});

export const metadata = {
  title: "Codeluxe",
  description: "Generated by create next app",
};

export const viewport = {
  themeColor: "var(--background)",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${montserrat.className} antialiased`}>
        <div className="fixed inset-0 -z-10 h-full w-full bg-[linear-gradient(to_right,#fff1_1px,transparent_1px),linear-gradient(to_bottom,#fff1_1px,transparent_1px)] bg-[size:7rem_12rem]"></div>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
